name: Demo CI tests
on:
    push:
        branches:
            - features/full-review
    workflow_dispatch:
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - name: Print to console
              run:  echo "Hello GH actions!"
            - name: Print a few lines
              run: |
                echo First line
                echo "Second line"
                echo Third line
